n = int()
print("n:", type(n))
f = float()
print("f:", type(f))
s = str()
print("s:", type(s))
b = bool()
print("b:", type(b))
l = list()
print("l:", type(l))
t = tuple()
print("t:", type(t))
d = dict()
print("d:", type(d))
s = set()
print("s:", type(s))
c = complex()
print("c:", type(c))